<?php

namespace App\Models;

class Constants {

    public function getConstants() {
        return [
            "USER_ALREADY_EXIST" => "User Already Exists with this number/email",
            "USER_CREATED" => "User Created Successfully!",
            "UNAUTHORIZED_CREDENTIALS" => "Invalid Username or Password",
            "USER_NOT_EXIST" => 'This User Does not Exist',
            "PASSWORD_MAIL_SENT" => "Password Reset Mail Sent",
            "SERVER_ERROR" => "Something Went Wrong! Try Again Later",
            "LOG_OUT" => "Successfully Logged Out!",
            "PROFILE_UPDATE" => "Profile Info Updated Successfully!",
            "UPLOAD_ONLY_IMAGE"=>"Upload Only One Image",
            "CART_EXISTS" => "This Product is Already Exists on the Cart!",
            "CART_ADDED" => "Cart Added Successfully!",
            "CART_UPDATE" => "Cart Updated Successfully!",
            "DELETE_CART" => "Cart Item Deleted!",
            "CATEGORY_ADD" => "Category Added!",
            "CATEGORY_UPDATE" => "Category Updated!",
            "DELETE_CATEGORY" => "Category Deleted!",
            "ADD_FEEDBACK" => "Feedback Added!",
            "ADD_PRODUCT" => "Product Added!",
            "UPDATE_PRODUCT" => "Product Updated!",
            "PRODUCT_STOCK_ADD" => "Product Stock Added!",
            "PRODUCT_STOCK_UPDATE" => "Product Stock Updated!",
            "PRODUCT_STOCK_DELETE" => "Product Stock Deleted!",
            "SUB_CATEGORY_ADD" => "Sub Category Added!",
            "SUB_CATEGORY_UPDATE" => "Sub Category Updated!",
            "SUB_CATEGORY_DELETE" => "Sub Category Deleted!",
            "PRODUCT_WEIGHT_ADD" => "Product Weight Added!",
            "PRODUCT_WEIGHT_UPDATE" => "Product Weight Updated!",
            "DELETE_PRODUCT_WEIGHT" => "Product Weight Deleted!",
            "USER_ADDRESS_ADD" => "User Address Added!",
            "USER_ADDRESS_UPDATE" => "User Address Updated!",
            "USER_ADDRESS_DELETE" => "User Address Deleted!",
            "SELECT_QUANTITY" => "You Should Select Atleast One Quantity!",
            "ADDRESS_CHECK" => "Can Not Add More Than 3 Address",
            "EDIT_PROFILE"=>"User Profile Updated",
            "PAYMENT_SUCCESS"=>"Payment is Successfull",
            "PAYMENT_FAILURE"=>"Payment is Failed",
            "PAYMENT_CANCELLED"=>"Payment is Cancelled",
            "UNAUTHORIZED_USER"=>"Unauthorized User",
            "UPDATE_PASSWORD"=>"Password Updated Successfully!",
            "ADD_ABOUT"=>"About Content Added Successfully!",
            "UPDATE_ABOUT"=>"About Content Updated Successfully!",
            "DELETE_ABOUT"=>"About Content Deleted Successfully!",
            "RAZOR_PAY_API_KEY" => env("RAZOR_PAY_API_KEY"),
            "RAZOR_PAY_SECRET" => env("RAZOR_PAY_SECRET"),
            "CONTACT_US_MAIL" => "Your Contact Mail Sent!",
            "BANNER_IMAGE_ADD" => "Bannner Image Details Added!",
            "BANNER_UPDATE" => "Bannner Details Updated!",
            "BANNER_DELETE" => "Bannner Details Deleted!",
            "DELETE_PRODUCT" => "PRODUCT DELETED SUCCESSFULLY!",
            "DELETE_PRODUCT_IMAGE" => "PRODUCT IMAGE DELETED SUCCESSFULLY!",
            "UPDATE_AWB_CODE" => "AWB Code Updated Successfully!",
            "ORDER_CANCEL_REJECT" => "Sorry, You Can Not Cancel Your Order!",
            "ORDER_CANCEL_ACCEPT" => "Your Order Cancelled Successfully!",
            "ORDER_CANCEL_MAIL" => "<p style='text-align:justify;'>
                                    Your Amount will be refunded soon! </p></br>",
            "PROFILE_PHOTO_UPDATE" => "Profile Photo Updated!",
            "UPDATE_STATUS_ACTIVE"=>"Banner Status Activated!",
            "UPDATE_STATUS_DEACTIVE"=>"Banner Status Deactivated!",
            "SELECT_ADDRESS"=>"Please Select Address!",
            "IMAGE_UPLOAD_EXCEED"=>"You Can Not Upload More Than Five images!",
            "CATEGORY_IMAGE_UPLOAD_EXCEED"=>"You Can Not Upload More Than One image!",
            "WEIGHT_ERROR_MSG"=>"You Can Only Buy 2kg at a time!",
            "WEIGHT_LIMIT"=>env("WEIGHT_LIMIT"),
            "MAIL_USERNAME"=>env("MAIL_USERNAME"),
            "ADD_TAG"=>"Tag Added Successfully!",
            "STORE_MAIL_MESSAGE"=>"Mail Message Submitted!",
            "EDIT_MAIL_MESSAGE"=>"Mail Message Updated!",
            "DELETE_MAIL_MESSAGE"=>"Mail Message Deleted!",
            "PRODUCT_TAG_DELETE"=>"Product Tag Deleted!",
            "TAG_UPLOAD_EXCEED"=>"You Can Not Add More Than Five Tags!",
            "PRODUCT_WEIGHT_UPDATE"=>"Product Weight Updated!",
            "WEIGHT_EXISTS"=>"Product Weight Exists,Please Update!",
            "NEW_WEIGHT_INSERTED"=>"New Weight Inserted!",
            "WEB_HOOK_PAYMENT_AUTHORIZED"=>"Payment is Authorized!",
            "WEB_HOOK_PAYMENT_CAPTURED"=>"Payment is Successfull!",
            "WEB_HOOK_PAYMENT_FAIL"=>"Payment is Failed!",
            "ORDER_FAILED"=>"if any money debited, Payment Will Be Refunded within Seven Days!",
            "PRODUCT_STATUS_ACTIVE"=>"Product Status Activated!",
            "PRODUCT_STATUS_DEACTIVE"=>"Product Status Deactivated!",
            "STOCK_ERROR"=>"Product is Out of Stock!",
            "PRODUCT_NOT_AVAILABLE"=>"Product is Not Available!",
            "NO_PRODUCT"=>"This Product is no longer Available!",
            "TOKEN_NOT_FOUND_EXPIRED"=>"Unauthenticated!",
            "USER_PROFILE_UPDATE" => "User Profile Details Updated Successfully!",
            "ADD_MID_HEADER" => "Mid Header Added Successfully!",
            "UPDATE_MID_HEADER" => "Mid Header Added Successfully!",
            "WEIGHT_DELETE_ERROR" => "Must keep atleast one product Weight",
            "MASTER_WEIGHT_ADD" => "Master Weight Added!",
            "MASTER_WEIGHT_UPDATE"=>"Master Weight Updated!",
            "MASTER_WEIGHT_DELETE"=>"Master Weight Deleted!",
            "MASTER_WEIGHT_EXISTS"=>"Weight Already Exists!"

        ];
    }
}
